[toolchain]
profile = "minimal"
channel = "nightly-2024-05-02"
components = ["rust-src", "llvm-tools", "rustfmt", "clippy"]
targets = ["x86_64-unknown-none", "riscv64gc-unknown-none-elf", "aarch64-unknown-none-softfloat", "loongarch64-unknown-none-softfloat"]
