[package]
name = "page_table_entry"
edition = "2024"
description = "Page table entry definition for various hardware architectures"
documentation = "https://docs.rs/page_table_entry"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
arm-el2 = []

[dependencies]
bitflags = "2.6"
memory_addr = "0.3"

[target.'cfg(any(target_arch = "aarch64", doc))'.dependencies]
aarch64-cpu = "9.4"

[target.'cfg(any(target_arch = "x86_64", doc))'.dependencies]
x86_64 = "0.15"

[package.metadata.docs.rs]
rustc-args = [ "--cfg" , "doc"]
